package com.chinasofti.custSatisSurvey.dao;

import com.chinasofti.custSatisSurvey.pojo.TSurvey;
import com.chinasofti.custSatisSurvey.pojo.TSurveyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TSurveyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	long countByExample(TSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int deleteByExample(TSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int insert(TSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int insertSelective(TSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	List<TSurvey> selectByExample(TSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	TSurvey selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TSurvey record, @Param("example") TSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TSurvey record, @Param("example") TSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TSurvey record);

	//insert by selectKey(after)
	int insert3(TSurvey record);

}