package com.chinasofti.custSatisSurvey.pojo;

import java.util.ArrayList;
import java.util.List;

public class TConfigExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_config
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_config
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_config
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public TConfigExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_config
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_config
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOptionValueIsNull() {
			addCriterion("option_value is null");
			return (Criteria) this;
		}

		public Criteria andOptionValueIsNotNull() {
			addCriterion("option_value is not null");
			return (Criteria) this;
		}

		public Criteria andOptionValueEqualTo(String value) {
			addCriterion("option_value =", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueNotEqualTo(String value) {
			addCriterion("option_value <>", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueGreaterThan(String value) {
			addCriterion("option_value >", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueGreaterThanOrEqualTo(String value) {
			addCriterion("option_value >=", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueLessThan(String value) {
			addCriterion("option_value <", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueLessThanOrEqualTo(String value) {
			addCriterion("option_value <=", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueLike(String value) {
			addCriterion("option_value like", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueNotLike(String value) {
			addCriterion("option_value not like", value, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueIn(List<String> values) {
			addCriterion("option_value in", values, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueNotIn(List<String> values) {
			addCriterion("option_value not in", values, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueBetween(String value1, String value2) {
			addCriterion("option_value between", value1, value2, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionValueNotBetween(String value1, String value2) {
			addCriterion("option_value not between", value1, value2, "optionValue");
			return (Criteria) this;
		}

		public Criteria andOptionTextIsNull() {
			addCriterion("option_text is null");
			return (Criteria) this;
		}

		public Criteria andOptionTextIsNotNull() {
			addCriterion("option_text is not null");
			return (Criteria) this;
		}

		public Criteria andOptionTextEqualTo(String value) {
			addCriterion("option_text =", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextNotEqualTo(String value) {
			addCriterion("option_text <>", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextGreaterThan(String value) {
			addCriterion("option_text >", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextGreaterThanOrEqualTo(String value) {
			addCriterion("option_text >=", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextLessThan(String value) {
			addCriterion("option_text <", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextLessThanOrEqualTo(String value) {
			addCriterion("option_text <=", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextLike(String value) {
			addCriterion("option_text like", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextNotLike(String value) {
			addCriterion("option_text not like", value, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextIn(List<String> values) {
			addCriterion("option_text in", values, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextNotIn(List<String> values) {
			addCriterion("option_text not in", values, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextBetween(String value1, String value2) {
			addCriterion("option_text between", value1, value2, "optionText");
			return (Criteria) this;
		}

		public Criteria andOptionTextNotBetween(String value1, String value2) {
			addCriterion("option_text not between", value1, value2, "optionText");
			return (Criteria) this;
		}

		public Criteria andConfigTypeIsNull() {
			addCriterion("config_type is null");
			return (Criteria) this;
		}

		public Criteria andConfigTypeIsNotNull() {
			addCriterion("config_type is not null");
			return (Criteria) this;
		}

		public Criteria andConfigTypeEqualTo(String value) {
			addCriterion("config_type =", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeNotEqualTo(String value) {
			addCriterion("config_type <>", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeGreaterThan(String value) {
			addCriterion("config_type >", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeGreaterThanOrEqualTo(String value) {
			addCriterion("config_type >=", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeLessThan(String value) {
			addCriterion("config_type <", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeLessThanOrEqualTo(String value) {
			addCriterion("config_type <=", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeLike(String value) {
			addCriterion("config_type like", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeNotLike(String value) {
			addCriterion("config_type not like", value, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeIn(List<String> values) {
			addCriterion("config_type in", values, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeNotIn(List<String> values) {
			addCriterion("config_type not in", values, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeBetween(String value1, String value2) {
			addCriterion("config_type between", value1, value2, "configType");
			return (Criteria) this;
		}

		public Criteria andConfigTypeNotBetween(String value1, String value2) {
			addCriterion("config_type not between", value1, value2, "configType");
			return (Criteria) this;
		}

		public Criteria andParentIsNull() {
			addCriterion("parent is null");
			return (Criteria) this;
		}

		public Criteria andParentIsNotNull() {
			addCriterion("parent is not null");
			return (Criteria) this;
		}

		public Criteria andParentEqualTo(String value) {
			addCriterion("parent =", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotEqualTo(String value) {
			addCriterion("parent <>", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentGreaterThan(String value) {
			addCriterion("parent >", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentGreaterThanOrEqualTo(String value) {
			addCriterion("parent >=", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLessThan(String value) {
			addCriterion("parent <", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLessThanOrEqualTo(String value) {
			addCriterion("parent <=", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLike(String value) {
			addCriterion("parent like", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotLike(String value) {
			addCriterion("parent not like", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentIn(List<String> values) {
			addCriterion("parent in", values, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotIn(List<String> values) {
			addCriterion("parent not in", values, "parent");
			return (Criteria) this;
		}

		public Criteria andParentBetween(String value1, String value2) {
			addCriterion("parent between", value1, value2, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotBetween(String value1, String value2) {
			addCriterion("parent not between", value1, value2, "parent");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_config
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}