package com.chinasofti.custSatisSurvey.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_config
 */
public class TConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_config.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_config.option_value
	 * @mbg.generated
	 */
	private String optionValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_config.option_text
	 * @mbg.generated
	 */
	private String optionText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_config.config_type
	 * @mbg.generated
	 */
	private String configType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_config.parent
	 * @mbg.generated
	 */
	private String parent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_config.id
	 * @return  the value of t_config.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_config.id
	 * @param id  the value for t_config.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_config.option_value
	 * @return  the value of t_config.option_value
	 * @mbg.generated
	 */
	public String getOptionValue() {
		return optionValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_config.option_value
	 * @param optionValue  the value for t_config.option_value
	 * @mbg.generated
	 */
	public void setOptionValue(String optionValue) {
		this.optionValue = optionValue == null ? null : optionValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_config.option_text
	 * @return  the value of t_config.option_text
	 * @mbg.generated
	 */
	public String getOptionText() {
		return optionText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_config.option_text
	 * @param optionText  the value for t_config.option_text
	 * @mbg.generated
	 */
	public void setOptionText(String optionText) {
		this.optionText = optionText == null ? null : optionText.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_config.config_type
	 * @return  the value of t_config.config_type
	 * @mbg.generated
	 */
	public String getConfigType() {
		return configType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_config.config_type
	 * @param configType  the value for t_config.config_type
	 * @mbg.generated
	 */
	public void setConfigType(String configType) {
		this.configType = configType == null ? null : configType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_config.parent
	 * @return  the value of t_config.parent
	 * @mbg.generated
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_config.parent
	 * @param parent  the value for t_config.parent
	 * @mbg.generated
	 */
	public void setParent(String parent) {
		this.parent = parent == null ? null : parent.trim();
	}
}