package com.chinasofti.custSatisSurvey.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_survey
 */
public class TSurvey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.cust_name
	 * @mbg.generated
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.eval_person_dep
	 * @mbg.generated
	 */
	private String evalPersonDep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.eval_person_name
	 * @mbg.generated
	 */
	private String evalPersonName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.eval_date
	 * @mbg.generated
	 */
	private String evalDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.comprehensive_eval_1
	 * @mbg.generated
	 */
	private String comprehensiveEval1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.comprehensive_eval_1_reason
	 * @mbg.generated
	 */
	private String comprehensiveEval1Reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_1_1
	 * @mbg.generated
	 */
	private String specialEval11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_1_2
	 * @mbg.generated
	 */
	private String specialEval12;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_1_detail
	 * @mbg.generated
	 */
	private String specialEval1Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_2_1
	 * @mbg.generated
	 */
	private String specialEval21;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_2_2
	 * @mbg.generated
	 */
	private String specialEval22;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_2_3
	 * @mbg.generated
	 */
	private String specialEval23;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_2_detail
	 * @mbg.generated
	 */
	private String specialEval2Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_1
	 * @mbg.generated
	 */
	private String specialEval31;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_2
	 * @mbg.generated
	 */
	private String specialEval32;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_detail
	 * @mbg.generated
	 */
	private String specialEval3Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4_1
	 * @mbg.generated
	 */
	private String specialEval41;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4_2
	 * @mbg.generated
	 */
	private String specialEval42;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4_detail
	 * @mbg.generated
	 */
	private String specialEval4Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_5_1
	 * @mbg.generated
	 */
	private String specialEval51;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_5_2
	 * @mbg.generated
	 */
	private String specialEval52;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_5_detail
	 * @mbg.generated
	 */
	private String specialEval5Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_6_1
	 * @mbg.generated
	 */
	private String specialEval61;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_6_2
	 * @mbg.generated
	 */
	private String specialEval62;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_6_detail
	 * @mbg.generated
	 */
	private String specialEval6Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_7_1
	 * @mbg.generated
	 */
	private String specialEval71;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_7_2
	 * @mbg.generated
	 */
	private String specialEval72;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_7_detail
	 * @mbg.generated
	 */
	private String specialEval7Detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_8
	 * @mbg.generated
	 */
	private String specialEval8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_9
	 * @mbg.generated
	 */
	private String specialEval9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.lob
	 * @mbg.generated
	 */
	private String lob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.surveytype
	 * @mbg.generated
	 */
	private String surveytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_5
	 * @mbg.generated
	 */
	private String specialEval5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_6
	 * @mbg.generated
	 */
	private String specialEval6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_2_4
	 * @mbg.generated
	 */
	private String specialEval24;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_3
	 * @mbg.generated
	 */
	private String specialEval33;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_4
	 * @mbg.generated
	 */
	private String specialEval34;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3_5
	 * @mbg.generated
	 */
	private String specialEval35;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4_3
	 * @mbg.generated
	 */
	private String specialEval43;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4_4
	 * @mbg.generated
	 */
	private String specialEval44;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_3
	 * @mbg.generated
	 */
	private String specialEval3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.special_eval_4
	 * @mbg.generated
	 */
	private String specialEval4;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.id
	 * @return  the value of t_survey.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.id
	 * @param id  the value for t_survey.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.cust_name
	 * @return  the value of t_survey.cust_name
	 * @mbg.generated
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.cust_name
	 * @param custName  the value for t_survey.cust_name
	 * @mbg.generated
	 */
	public void setCustName(String custName) {
		this.custName = custName == null ? null : custName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.eval_person_dep
	 * @return  the value of t_survey.eval_person_dep
	 * @mbg.generated
	 */
	public String getEvalPersonDep() {
		return evalPersonDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.eval_person_dep
	 * @param evalPersonDep  the value for t_survey.eval_person_dep
	 * @mbg.generated
	 */
	public void setEvalPersonDep(String evalPersonDep) {
		this.evalPersonDep = evalPersonDep == null ? null : evalPersonDep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.eval_person_name
	 * @return  the value of t_survey.eval_person_name
	 * @mbg.generated
	 */
	public String getEvalPersonName() {
		return evalPersonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.eval_person_name
	 * @param evalPersonName  the value for t_survey.eval_person_name
	 * @mbg.generated
	 */
	public void setEvalPersonName(String evalPersonName) {
		this.evalPersonName = evalPersonName == null ? null : evalPersonName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.eval_date
	 * @return  the value of t_survey.eval_date
	 * @mbg.generated
	 */
	public String getEvalDate() {
		return evalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.eval_date
	 * @param evalDate  the value for t_survey.eval_date
	 * @mbg.generated
	 */
	public void setEvalDate(String evalDate) {
		this.evalDate = evalDate == null ? null : evalDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.comprehensive_eval_1
	 * @return  the value of t_survey.comprehensive_eval_1
	 * @mbg.generated
	 */
	public String getComprehensiveEval1() {
		return comprehensiveEval1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.comprehensive_eval_1
	 * @param comprehensiveEval1  the value for t_survey.comprehensive_eval_1
	 * @mbg.generated
	 */
	public void setComprehensiveEval1(String comprehensiveEval1) {
		this.comprehensiveEval1 = comprehensiveEval1 == null ? null : comprehensiveEval1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.comprehensive_eval_1_reason
	 * @return  the value of t_survey.comprehensive_eval_1_reason
	 * @mbg.generated
	 */
	public String getComprehensiveEval1Reason() {
		return comprehensiveEval1Reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.comprehensive_eval_1_reason
	 * @param comprehensiveEval1Reason  the value for t_survey.comprehensive_eval_1_reason
	 * @mbg.generated
	 */
	public void setComprehensiveEval1Reason(String comprehensiveEval1Reason) {
		this.comprehensiveEval1Reason = comprehensiveEval1Reason == null ? null : comprehensiveEval1Reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_1_1
	 * @return  the value of t_survey.special_eval_1_1
	 * @mbg.generated
	 */
	public String getSpecialEval11() {
		return specialEval11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_1_1
	 * @param specialEval11  the value for t_survey.special_eval_1_1
	 * @mbg.generated
	 */
	public void setSpecialEval11(String specialEval11) {
		this.specialEval11 = specialEval11 == null ? null : specialEval11.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_1_2
	 * @return  the value of t_survey.special_eval_1_2
	 * @mbg.generated
	 */
	public String getSpecialEval12() {
		return specialEval12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_1_2
	 * @param specialEval12  the value for t_survey.special_eval_1_2
	 * @mbg.generated
	 */
	public void setSpecialEval12(String specialEval12) {
		this.specialEval12 = specialEval12 == null ? null : specialEval12.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_1_detail
	 * @return  the value of t_survey.special_eval_1_detail
	 * @mbg.generated
	 */
	public String getSpecialEval1Detail() {
		return specialEval1Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_1_detail
	 * @param specialEval1Detail  the value for t_survey.special_eval_1_detail
	 * @mbg.generated
	 */
	public void setSpecialEval1Detail(String specialEval1Detail) {
		this.specialEval1Detail = specialEval1Detail == null ? null : specialEval1Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_2_1
	 * @return  the value of t_survey.special_eval_2_1
	 * @mbg.generated
	 */
	public String getSpecialEval21() {
		return specialEval21;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_2_1
	 * @param specialEval21  the value for t_survey.special_eval_2_1
	 * @mbg.generated
	 */
	public void setSpecialEval21(String specialEval21) {
		this.specialEval21 = specialEval21 == null ? null : specialEval21.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_2_2
	 * @return  the value of t_survey.special_eval_2_2
	 * @mbg.generated
	 */
	public String getSpecialEval22() {
		return specialEval22;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_2_2
	 * @param specialEval22  the value for t_survey.special_eval_2_2
	 * @mbg.generated
	 */
	public void setSpecialEval22(String specialEval22) {
		this.specialEval22 = specialEval22 == null ? null : specialEval22.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_2_3
	 * @return  the value of t_survey.special_eval_2_3
	 * @mbg.generated
	 */
	public String getSpecialEval23() {
		return specialEval23;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_2_3
	 * @param specialEval23  the value for t_survey.special_eval_2_3
	 * @mbg.generated
	 */
	public void setSpecialEval23(String specialEval23) {
		this.specialEval23 = specialEval23 == null ? null : specialEval23.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_2_detail
	 * @return  the value of t_survey.special_eval_2_detail
	 * @mbg.generated
	 */
	public String getSpecialEval2Detail() {
		return specialEval2Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_2_detail
	 * @param specialEval2Detail  the value for t_survey.special_eval_2_detail
	 * @mbg.generated
	 */
	public void setSpecialEval2Detail(String specialEval2Detail) {
		this.specialEval2Detail = specialEval2Detail == null ? null : specialEval2Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_1
	 * @return  the value of t_survey.special_eval_3_1
	 * @mbg.generated
	 */
	public String getSpecialEval31() {
		return specialEval31;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_1
	 * @param specialEval31  the value for t_survey.special_eval_3_1
	 * @mbg.generated
	 */
	public void setSpecialEval31(String specialEval31) {
		this.specialEval31 = specialEval31 == null ? null : specialEval31.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_2
	 * @return  the value of t_survey.special_eval_3_2
	 * @mbg.generated
	 */
	public String getSpecialEval32() {
		return specialEval32;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_2
	 * @param specialEval32  the value for t_survey.special_eval_3_2
	 * @mbg.generated
	 */
	public void setSpecialEval32(String specialEval32) {
		this.specialEval32 = specialEval32 == null ? null : specialEval32.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_detail
	 * @return  the value of t_survey.special_eval_3_detail
	 * @mbg.generated
	 */
	public String getSpecialEval3Detail() {
		return specialEval3Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_detail
	 * @param specialEval3Detail  the value for t_survey.special_eval_3_detail
	 * @mbg.generated
	 */
	public void setSpecialEval3Detail(String specialEval3Detail) {
		this.specialEval3Detail = specialEval3Detail == null ? null : specialEval3Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4_1
	 * @return  the value of t_survey.special_eval_4_1
	 * @mbg.generated
	 */
	public String getSpecialEval41() {
		return specialEval41;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4_1
	 * @param specialEval41  the value for t_survey.special_eval_4_1
	 * @mbg.generated
	 */
	public void setSpecialEval41(String specialEval41) {
		this.specialEval41 = specialEval41 == null ? null : specialEval41.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4_2
	 * @return  the value of t_survey.special_eval_4_2
	 * @mbg.generated
	 */
	public String getSpecialEval42() {
		return specialEval42;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4_2
	 * @param specialEval42  the value for t_survey.special_eval_4_2
	 * @mbg.generated
	 */
	public void setSpecialEval42(String specialEval42) {
		this.specialEval42 = specialEval42 == null ? null : specialEval42.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4_detail
	 * @return  the value of t_survey.special_eval_4_detail
	 * @mbg.generated
	 */
	public String getSpecialEval4Detail() {
		return specialEval4Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4_detail
	 * @param specialEval4Detail  the value for t_survey.special_eval_4_detail
	 * @mbg.generated
	 */
	public void setSpecialEval4Detail(String specialEval4Detail) {
		this.specialEval4Detail = specialEval4Detail == null ? null : specialEval4Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_5_1
	 * @return  the value of t_survey.special_eval_5_1
	 * @mbg.generated
	 */
	public String getSpecialEval51() {
		return specialEval51;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_5_1
	 * @param specialEval51  the value for t_survey.special_eval_5_1
	 * @mbg.generated
	 */
	public void setSpecialEval51(String specialEval51) {
		this.specialEval51 = specialEval51 == null ? null : specialEval51.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_5_2
	 * @return  the value of t_survey.special_eval_5_2
	 * @mbg.generated
	 */
	public String getSpecialEval52() {
		return specialEval52;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_5_2
	 * @param specialEval52  the value for t_survey.special_eval_5_2
	 * @mbg.generated
	 */
	public void setSpecialEval52(String specialEval52) {
		this.specialEval52 = specialEval52 == null ? null : specialEval52.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_5_detail
	 * @return  the value of t_survey.special_eval_5_detail
	 * @mbg.generated
	 */
	public String getSpecialEval5Detail() {
		return specialEval5Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_5_detail
	 * @param specialEval5Detail  the value for t_survey.special_eval_5_detail
	 * @mbg.generated
	 */
	public void setSpecialEval5Detail(String specialEval5Detail) {
		this.specialEval5Detail = specialEval5Detail == null ? null : specialEval5Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_6_1
	 * @return  the value of t_survey.special_eval_6_1
	 * @mbg.generated
	 */
	public String getSpecialEval61() {
		return specialEval61;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_6_1
	 * @param specialEval61  the value for t_survey.special_eval_6_1
	 * @mbg.generated
	 */
	public void setSpecialEval61(String specialEval61) {
		this.specialEval61 = specialEval61 == null ? null : specialEval61.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_6_2
	 * @return  the value of t_survey.special_eval_6_2
	 * @mbg.generated
	 */
	public String getSpecialEval62() {
		return specialEval62;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_6_2
	 * @param specialEval62  the value for t_survey.special_eval_6_2
	 * @mbg.generated
	 */
	public void setSpecialEval62(String specialEval62) {
		this.specialEval62 = specialEval62 == null ? null : specialEval62.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_6_detail
	 * @return  the value of t_survey.special_eval_6_detail
	 * @mbg.generated
	 */
	public String getSpecialEval6Detail() {
		return specialEval6Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_6_detail
	 * @param specialEval6Detail  the value for t_survey.special_eval_6_detail
	 * @mbg.generated
	 */
	public void setSpecialEval6Detail(String specialEval6Detail) {
		this.specialEval6Detail = specialEval6Detail == null ? null : specialEval6Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_7_1
	 * @return  the value of t_survey.special_eval_7_1
	 * @mbg.generated
	 */
	public String getSpecialEval71() {
		return specialEval71;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_7_1
	 * @param specialEval71  the value for t_survey.special_eval_7_1
	 * @mbg.generated
	 */
	public void setSpecialEval71(String specialEval71) {
		this.specialEval71 = specialEval71 == null ? null : specialEval71.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_7_2
	 * @return  the value of t_survey.special_eval_7_2
	 * @mbg.generated
	 */
	public String getSpecialEval72() {
		return specialEval72;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_7_2
	 * @param specialEval72  the value for t_survey.special_eval_7_2
	 * @mbg.generated
	 */
	public void setSpecialEval72(String specialEval72) {
		this.specialEval72 = specialEval72 == null ? null : specialEval72.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_7_detail
	 * @return  the value of t_survey.special_eval_7_detail
	 * @mbg.generated
	 */
	public String getSpecialEval7Detail() {
		return specialEval7Detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_7_detail
	 * @param specialEval7Detail  the value for t_survey.special_eval_7_detail
	 * @mbg.generated
	 */
	public void setSpecialEval7Detail(String specialEval7Detail) {
		this.specialEval7Detail = specialEval7Detail == null ? null : specialEval7Detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_8
	 * @return  the value of t_survey.special_eval_8
	 * @mbg.generated
	 */
	public String getSpecialEval8() {
		return specialEval8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_8
	 * @param specialEval8  the value for t_survey.special_eval_8
	 * @mbg.generated
	 */
	public void setSpecialEval8(String specialEval8) {
		this.specialEval8 = specialEval8 == null ? null : specialEval8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_9
	 * @return  the value of t_survey.special_eval_9
	 * @mbg.generated
	 */
	public String getSpecialEval9() {
		return specialEval9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_9
	 * @param specialEval9  the value for t_survey.special_eval_9
	 * @mbg.generated
	 */
	public void setSpecialEval9(String specialEval9) {
		this.specialEval9 = specialEval9 == null ? null : specialEval9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.lob
	 * @return  the value of t_survey.lob
	 * @mbg.generated
	 */
	public String getLob() {
		return lob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.lob
	 * @param lob  the value for t_survey.lob
	 * @mbg.generated
	 */
	public void setLob(String lob) {
		this.lob = lob == null ? null : lob.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.surveytype
	 * @return  the value of t_survey.surveytype
	 * @mbg.generated
	 */
	public String getSurveytype() {
		return surveytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.surveytype
	 * @param surveytype  the value for t_survey.surveytype
	 * @mbg.generated
	 */
	public void setSurveytype(String surveytype) {
		this.surveytype = surveytype == null ? null : surveytype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_5
	 * @return  the value of t_survey.special_eval_5
	 * @mbg.generated
	 */
	public String getSpecialEval5() {
		return specialEval5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_5
	 * @param specialEval5  the value for t_survey.special_eval_5
	 * @mbg.generated
	 */
	public void setSpecialEval5(String specialEval5) {
		this.specialEval5 = specialEval5 == null ? null : specialEval5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_6
	 * @return  the value of t_survey.special_eval_6
	 * @mbg.generated
	 */
	public String getSpecialEval6() {
		return specialEval6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_6
	 * @param specialEval6  the value for t_survey.special_eval_6
	 * @mbg.generated
	 */
	public void setSpecialEval6(String specialEval6) {
		this.specialEval6 = specialEval6 == null ? null : specialEval6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_2_4
	 * @return  the value of t_survey.special_eval_2_4
	 * @mbg.generated
	 */
	public String getSpecialEval24() {
		return specialEval24;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_2_4
	 * @param specialEval24  the value for t_survey.special_eval_2_4
	 * @mbg.generated
	 */
	public void setSpecialEval24(String specialEval24) {
		this.specialEval24 = specialEval24 == null ? null : specialEval24.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_3
	 * @return  the value of t_survey.special_eval_3_3
	 * @mbg.generated
	 */
	public String getSpecialEval33() {
		return specialEval33;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_3
	 * @param specialEval33  the value for t_survey.special_eval_3_3
	 * @mbg.generated
	 */
	public void setSpecialEval33(String specialEval33) {
		this.specialEval33 = specialEval33 == null ? null : specialEval33.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_4
	 * @return  the value of t_survey.special_eval_3_4
	 * @mbg.generated
	 */
	public String getSpecialEval34() {
		return specialEval34;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_4
	 * @param specialEval34  the value for t_survey.special_eval_3_4
	 * @mbg.generated
	 */
	public void setSpecialEval34(String specialEval34) {
		this.specialEval34 = specialEval34 == null ? null : specialEval34.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3_5
	 * @return  the value of t_survey.special_eval_3_5
	 * @mbg.generated
	 */
	public String getSpecialEval35() {
		return specialEval35;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3_5
	 * @param specialEval35  the value for t_survey.special_eval_3_5
	 * @mbg.generated
	 */
	public void setSpecialEval35(String specialEval35) {
		this.specialEval35 = specialEval35 == null ? null : specialEval35.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4_3
	 * @return  the value of t_survey.special_eval_4_3
	 * @mbg.generated
	 */
	public String getSpecialEval43() {
		return specialEval43;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4_3
	 * @param specialEval43  the value for t_survey.special_eval_4_3
	 * @mbg.generated
	 */
	public void setSpecialEval43(String specialEval43) {
		this.specialEval43 = specialEval43 == null ? null : specialEval43.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4_4
	 * @return  the value of t_survey.special_eval_4_4
	 * @mbg.generated
	 */
	public String getSpecialEval44() {
		return specialEval44;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4_4
	 * @param specialEval44  the value for t_survey.special_eval_4_4
	 * @mbg.generated
	 */
	public void setSpecialEval44(String specialEval44) {
		this.specialEval44 = specialEval44 == null ? null : specialEval44.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_3
	 * @return  the value of t_survey.special_eval_3
	 * @mbg.generated
	 */
	public String getSpecialEval3() {
		return specialEval3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_3
	 * @param specialEval3  the value for t_survey.special_eval_3
	 * @mbg.generated
	 */
	public void setSpecialEval3(String specialEval3) {
		this.specialEval3 = specialEval3 == null ? null : specialEval3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.special_eval_4
	 * @return  the value of t_survey.special_eval_4
	 * @mbg.generated
	 */
	public String getSpecialEval4() {
		return specialEval4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.special_eval_4
	 * @param specialEval4  the value for t_survey.special_eval_4
	 * @mbg.generated
	 */
	public void setSpecialEval4(String specialEval4) {
		this.specialEval4 = specialEval4 == null ? null : specialEval4.trim();
	}
}