package com.chinasofti.custSatisSurvey.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 */
public class TUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.lob
	 * @mbg.generated
	 */
	private String lob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usertype
	 * @mbg.generated
	 */
	private String usertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.surveytype
	 * @mbg.generated
	 */
	private String surveytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.custname
	 * @mbg.generated
	 */
	private String custname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.eval_person_dep
	 * @mbg.generated
	 */
	private String evalPersonDep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.eval_person_name
	 * @mbg.generated
	 */
	private String evalPersonName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_by
	 * @mbg.generated
	 */
	private Integer createBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.lob
	 * @return  the value of t_user.lob
	 * @mbg.generated
	 */
	public String getLob() {
		return lob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.lob
	 * @param lob  the value for t_user.lob
	 * @mbg.generated
	 */
	public void setLob(String lob) {
		this.lob = lob == null ? null : lob.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usertype
	 * @return  the value of t_user.usertype
	 * @mbg.generated
	 */
	public String getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usertype
	 * @param usertype  the value for t_user.usertype
	 * @mbg.generated
	 */
	public void setUsertype(String usertype) {
		this.usertype = usertype == null ? null : usertype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.surveytype
	 * @return  the value of t_user.surveytype
	 * @mbg.generated
	 */
	public String getSurveytype() {
		return surveytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.surveytype
	 * @param surveytype  the value for t_user.surveytype
	 * @mbg.generated
	 */
	public void setSurveytype(String surveytype) {
		this.surveytype = surveytype == null ? null : surveytype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.custname
	 * @return  the value of t_user.custname
	 * @mbg.generated
	 */
	public String getCustname() {
		return custname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.custname
	 * @param custname  the value for t_user.custname
	 * @mbg.generated
	 */
	public void setCustname(String custname) {
		this.custname = custname == null ? null : custname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.eval_person_dep
	 * @return  the value of t_user.eval_person_dep
	 * @mbg.generated
	 */
	public String getEvalPersonDep() {
		return evalPersonDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.eval_person_dep
	 * @param evalPersonDep  the value for t_user.eval_person_dep
	 * @mbg.generated
	 */
	public void setEvalPersonDep(String evalPersonDep) {
		this.evalPersonDep = evalPersonDep == null ? null : evalPersonDep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.eval_person_name
	 * @return  the value of t_user.eval_person_name
	 * @mbg.generated
	 */
	public String getEvalPersonName() {
		return evalPersonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.eval_person_name
	 * @param evalPersonName  the value for t_user.eval_person_name
	 * @mbg.generated
	 */
	public void setEvalPersonName(String evalPersonName) {
		this.evalPersonName = evalPersonName == null ? null : evalPersonName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_by
	 * @return  the value of t_user.create_by
	 * @mbg.generated
	 */
	public Integer getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_by
	 * @param createBy  the value for t_user.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}
}