package com.chinasofti.custSatisSurvey.pojo;

import java.util.ArrayList;
import java.util.List;

public class TUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public TUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andLobIsNull() {
			addCriterion("lob is null");
			return (Criteria) this;
		}

		public Criteria andLobIsNotNull() {
			addCriterion("lob is not null");
			return (Criteria) this;
		}

		public Criteria andLobEqualTo(String value) {
			addCriterion("lob =", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotEqualTo(String value) {
			addCriterion("lob <>", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThan(String value) {
			addCriterion("lob >", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThanOrEqualTo(String value) {
			addCriterion("lob >=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThan(String value) {
			addCriterion("lob <", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThanOrEqualTo(String value) {
			addCriterion("lob <=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLike(String value) {
			addCriterion("lob like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotLike(String value) {
			addCriterion("lob not like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobIn(List<String> values) {
			addCriterion("lob in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotIn(List<String> values) {
			addCriterion("lob not in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobBetween(String value1, String value2) {
			addCriterion("lob between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotBetween(String value1, String value2) {
			addCriterion("lob not between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNull() {
			addCriterion("usertype is null");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNotNull() {
			addCriterion("usertype is not null");
			return (Criteria) this;
		}

		public Criteria andUsertypeEqualTo(String value) {
			addCriterion("usertype =", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotEqualTo(String value) {
			addCriterion("usertype <>", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThan(String value) {
			addCriterion("usertype >", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThanOrEqualTo(String value) {
			addCriterion("usertype >=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThan(String value) {
			addCriterion("usertype <", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThanOrEqualTo(String value) {
			addCriterion("usertype <=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLike(String value) {
			addCriterion("usertype like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotLike(String value) {
			addCriterion("usertype not like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeIn(List<String> values) {
			addCriterion("usertype in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotIn(List<String> values) {
			addCriterion("usertype not in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeBetween(String value1, String value2) {
			addCriterion("usertype between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotBetween(String value1, String value2) {
			addCriterion("usertype not between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeIsNull() {
			addCriterion("surveytype is null");
			return (Criteria) this;
		}

		public Criteria andSurveytypeIsNotNull() {
			addCriterion("surveytype is not null");
			return (Criteria) this;
		}

		public Criteria andSurveytypeEqualTo(String value) {
			addCriterion("surveytype =", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeNotEqualTo(String value) {
			addCriterion("surveytype <>", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeGreaterThan(String value) {
			addCriterion("surveytype >", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeGreaterThanOrEqualTo(String value) {
			addCriterion("surveytype >=", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeLessThan(String value) {
			addCriterion("surveytype <", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeLessThanOrEqualTo(String value) {
			addCriterion("surveytype <=", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeLike(String value) {
			addCriterion("surveytype like", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeNotLike(String value) {
			addCriterion("surveytype not like", value, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeIn(List<String> values) {
			addCriterion("surveytype in", values, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeNotIn(List<String> values) {
			addCriterion("surveytype not in", values, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeBetween(String value1, String value2) {
			addCriterion("surveytype between", value1, value2, "surveytype");
			return (Criteria) this;
		}

		public Criteria andSurveytypeNotBetween(String value1, String value2) {
			addCriterion("surveytype not between", value1, value2, "surveytype");
			return (Criteria) this;
		}

		public Criteria andCustnameIsNull() {
			addCriterion("custname is null");
			return (Criteria) this;
		}

		public Criteria andCustnameIsNotNull() {
			addCriterion("custname is not null");
			return (Criteria) this;
		}

		public Criteria andCustnameEqualTo(String value) {
			addCriterion("custname =", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameNotEqualTo(String value) {
			addCriterion("custname <>", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameGreaterThan(String value) {
			addCriterion("custname >", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameGreaterThanOrEqualTo(String value) {
			addCriterion("custname >=", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameLessThan(String value) {
			addCriterion("custname <", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameLessThanOrEqualTo(String value) {
			addCriterion("custname <=", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameLike(String value) {
			addCriterion("custname like", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameNotLike(String value) {
			addCriterion("custname not like", value, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameIn(List<String> values) {
			addCriterion("custname in", values, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameNotIn(List<String> values) {
			addCriterion("custname not in", values, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameBetween(String value1, String value2) {
			addCriterion("custname between", value1, value2, "custname");
			return (Criteria) this;
		}

		public Criteria andCustnameNotBetween(String value1, String value2) {
			addCriterion("custname not between", value1, value2, "custname");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepIsNull() {
			addCriterion("eval_person_dep is null");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepIsNotNull() {
			addCriterion("eval_person_dep is not null");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepEqualTo(String value) {
			addCriterion("eval_person_dep =", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepNotEqualTo(String value) {
			addCriterion("eval_person_dep <>", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepGreaterThan(String value) {
			addCriterion("eval_person_dep >", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepGreaterThanOrEqualTo(String value) {
			addCriterion("eval_person_dep >=", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepLessThan(String value) {
			addCriterion("eval_person_dep <", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepLessThanOrEqualTo(String value) {
			addCriterion("eval_person_dep <=", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepLike(String value) {
			addCriterion("eval_person_dep like", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepNotLike(String value) {
			addCriterion("eval_person_dep not like", value, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepIn(List<String> values) {
			addCriterion("eval_person_dep in", values, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepNotIn(List<String> values) {
			addCriterion("eval_person_dep not in", values, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepBetween(String value1, String value2) {
			addCriterion("eval_person_dep between", value1, value2, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonDepNotBetween(String value1, String value2) {
			addCriterion("eval_person_dep not between", value1, value2, "evalPersonDep");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameIsNull() {
			addCriterion("eval_person_name is null");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameIsNotNull() {
			addCriterion("eval_person_name is not null");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameEqualTo(String value) {
			addCriterion("eval_person_name =", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameNotEqualTo(String value) {
			addCriterion("eval_person_name <>", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameGreaterThan(String value) {
			addCriterion("eval_person_name >", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameGreaterThanOrEqualTo(String value) {
			addCriterion("eval_person_name >=", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameLessThan(String value) {
			addCriterion("eval_person_name <", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameLessThanOrEqualTo(String value) {
			addCriterion("eval_person_name <=", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameLike(String value) {
			addCriterion("eval_person_name like", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameNotLike(String value) {
			addCriterion("eval_person_name not like", value, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameIn(List<String> values) {
			addCriterion("eval_person_name in", values, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameNotIn(List<String> values) {
			addCriterion("eval_person_name not in", values, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameBetween(String value1, String value2) {
			addCriterion("eval_person_name between", value1, value2, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andEvalPersonNameNotBetween(String value1, String value2) {
			addCriterion("eval_person_name not between", value1, value2, "evalPersonName");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(Integer value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(Integer value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(Integer value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(Integer value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(Integer value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<Integer> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<Integer> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(Integer value1, Integer value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}